#+Title: Preface

* A meandering introduction

This book grew from my notes and experience teaching the History of Psychology course at the [[https://uwaterloo.ca/][University of Waterloo]]. I started teaching this course in Jan 2008. 
I was assigned this course for a couple of reasons. Most importantly, I was the newest departmental member, and really had no idea what I could or should say yes and no to. 
Secondarily, I had a background in Neurology where eponyms [fn:eponym] are common. 
By virtue of my common use of the names of physicians of long ago, I was viewed as sufficiently historical.

I was very anxious that first year. 
While I knew a lot about the brain and behavior, my background was not psychology /per se/. 
Fortunately, I was deluged with examination copies of textbooks on the topics.
Many were very good. 
All were expensive.

They were also very similar.
Why shouldn't they be?
There is a canonical view of psychology as a science that goes back to [[http://www.abebooks.com/servlet/SearchResults?an=boring&sts=t&tn=history+of+experimental+psychology][Boring]].
The various books did not differ in content as much as they differed in style and in depth. 
There were small differences in coverage that usually revolved around how far back the author wanted to go into the philosophical origins, and occassionally in later movements, e.g. whether psychoanalysis was included.

That first year these books saved me.
I read many of them in developing and preparing my own lectures, and used the consistency of their treatments to help me organize my own content. 
Disappointed by the expense, and in an effort to avoid redundancy between the readings and the lectures, I chose a small, and relatively inexpensive [[http://bcs.wiley.com/he-bcs/Books?action=index&bcsId=4849&itemId=140513206X][textbook]] as the course's required text. 

What surprised me about these textbooks was that each year I kept getting more and more of them.
Why were so many redundant texts necessary?
Why were new editions released yearly?
My guess is money.
History of Psychology courses are common components of psychology curricula.
Each publisher wants their own offering.
Writing a widely adopted text can be very [[http://www.thestar.com/news/gta/2011/02/04/the_house_that_math_built.html][lucrative]] for the authors.
And by putting out a new edition every year, which given that new scholarship doesn't accumulate that rapidly for historical topics cannot be justified based on pedagogical principles, the re-use of books from previous terms is discouraged.
Looking at these editions from one year to the next I could often not tell what had changed.
Often the covers were the same.
I began to develop conspiracy theories.
When I saw that a collection of [[http://ca.wiley.com/WileyCDA/WileyTitle/productCd-EHEP000212.html][original articles, with annotations]], was selling for over $60 Canadian I began to feel that the students were being taken advantage of.

At one point in time this packaging and reselling of old works with commentary could have been justified, but not anymore.
This is the internet age, and there are wonderful resources for letting students read the original works easily.
In many cases the expiration of copyright allows for the originals to be redistributed. 
In most North American Universities the library's subscription allows access to repositories like [[http://www.jstor.org/][JSTOR]] that have all the old, classic psychology journals on line (the [[http://apa.org/pubs/journals/index.aspx][APA]] does this as well).
Why have my students pay $100 for a textbook and a collection of readings, when I could give them links to the originals and we could use our class time for discussion.

This practice had an uneven result. 
Some students participated, but many did not.
And while some read around the original material to fill in their background knowledge, many did not.
I wanted some core collection of facts that I could require them to know.

For the last two offerings this has been provided by [[http://www.cengage.com/search/productOverview.do?N=11+4294945456&Ntk=P_EPI&Ntt=213994572487746077113700970783323149&Ntx=mode+matchallpartial][Kardas]]. 
This publisher has allowed for me to have a selection of the chapters printed which saves the students money from not having to purchase the whole book.
In addition, they can buy on-line access to the chapters for even less.
Since this is not a book that most students will consult as a reference, that has seemed a cost efficient compromise.

But I am beginning to doubt whether even that is necessary.
As my collection of links to on-line resources, podcasts, original articles, obituaries, and archives grows, I am beginning to believe that a /textbook/ could be made of this material with some bridging text and commentary. 
While some students may need or want the social atmosphere of the classroom discussion for developing their own ideas, others may be satisfied with self-study. 
By making the materials available on-line and with a print on demand mechanism, students could decide for themselves on the format.
And since I assume that I am only one of many instructors stumbling down this road, others could make use of my materials either taken as a whole or by cutting and pasting with their own edits, changes, additions, and subtractions as they see fit.

Where I am now is that the book should be a guided tour through the history of psychology with many links to freely available material. 
I should explain what I think is interesting, and why.
I should explain why I chose what I chose.
But others should be free to grab the whole thing and make it their own.
That led me to put the book in a github repository.
Students should be able to read it on-line to answer a question, Wikipedia-like.
Or they should be able to print it out as a pdf.
Or, in this day of the e-reader, they should be able to generate a more friendly version of the file, e.g. epub.
Therefore, I am using the Sphinx documentation system to allow all these different formats to be generated from the same text.
And to make the material available without putting myself in the position of IT support and webmaster, I am using the readthedocs organization to host the materials. 
They are the only ones, really, that are spending any money to make these materials available.
If you use this material I hope you will consider supporting [[https://readthedocs.org/projects/history-of-psychology/][readthedocs]].

** Some technical comments

   If you clone the github repo (here) you will find several different file types.
   1. =.org= files. These are written using the [[http://orgmode.org/worg/org-tutorials/index.html][org-mode]] flavor of markup.  I know this markup flavor, and like it.  It makes use of [[https://www.gnu.org/software/emacs/][emacs]], which is my text editor of choice.  However, [[http://www.sphinx-doc.org/en/stable/tutorial.html][Sphinx]] makes use of restructured text files.  To create these I use an exporter to convert my =.org= files to =.rst= files.  If you are not an emacs user, you are not interested in org-mode, and you are only planning on making changes for yourself or your own fork then you should edit the =.rst= files directly.  If you want to contribute back to the project in the form of a pull-request, then you need to edit and give me =.org= files.
   2. =.rst= files. These are [[http://docutils.sourceforge.net/rst.html][restructured text files]].
   3. Sphinx takes the =.rst= files and converts them to =.html= for viewing on the web, to =.pdf= for printing (or viewing on line), and to =.epub= for e-readers.  You can view and read =.epub= on line as well.  For example, there is a [[https://addons.mozilla.org/en-US/firefox/addon/epubreader/][Firefox plugin]].
   4. After I edit everything on my local machine I export from =.org= to =.rst= and then use the Sphinx created ~make~ commands, such as ~make html~ to produce the =.html= files.  I then =commit= those changes to my local github repository (aka repo), and =push= that commit to the origin at [[https://github.com/brittAnderson/histPsychol][github.com]].  From there I can sync it to the [[https://readthedocs.org/projects/history-of-psychology/][readthedocs.org]] site. 

[fn:eponym] Here are a couple of classic examples.  The [[https://youtu.be/y4RFNz8tXl0][Babinski sign]] is seen normally in very young children, and later in life as evidence of upper motor neuron injury.  I believe I read somewhere that one of the first cases was in a trapeeze artist who fell and suffered a spinal injury, but I have never been able to find that source again.  But this is a nice demonstration of what I am talking about.  Here is an online version of the original report of Babinski: [[http://gallica.bnf.fr/ark:/12148/bpt6k6459605g/f225.image][Sur Le Réflexe Cutané Plantaire Dans Certaines Affections Organiques Du Stystème Nerveux Central]].  Another example is [[https://youtu.be/3l8MzgvHfig][Broca's aphasia]], which is named after the French surgeon and anthropologist who is most credited with demonstrating that it is the left cerebral hemisphere that is specialized for language. Here is an early report of the case of [[http://gallica.bnf.fr/ark:/12148/bpt6k6373571k/f416.image.r=paul%2520broca][Lelong]] : and a [[https://www.sfn.org/~/media/SfN/Documents/ClassicPapers/Language/broca.ashx][translation of his 1865 report (pdf)]].
