#+Title: What is Psychology?
#+Options: timestamp:nil


* What is psychology?

To productively study the history of a topic, especially if you wish to apply those lessons to contemporary practice, you must be clear on the nature of that topic in the first place. The answer to the question of what is psychology is not as easy as it might appear, and this is particularly true if you are relatively young or a newcomer. Psychology was not always as it appears today. While contemporary definitions reflect prevalence and practice they are not proscriptive or prescriptive. That means that you are free to apply an idiosyncratic definition, or emphasize older themes. In any of these cases you should decide exactly what it is you mean by the term psychology. That is the way to get the most practical and personally relevant information from your historical inquiry. Take a moment before reading on and write a one sentence definition of what psychology is. Then see how some others have defined it.
#+Begin_RST
.. raw:: pdf 

   Page Break

#+End_RST

** Aristotle

   #+ATTR_RST: :margin 4
   #+BEGIN_QUOTE
   psychology studies the soul (psuchê in Greek, or anima in Latin); so it naturally investigates all ensouled or animate beings. Standford Encyclopedia of Philosophy [[http://plato.stanford.edu/entries/aristotle-psychology/][Aristotle]] 300s BCE
   #+END_QUOTE
** John Stuart Mill
   
   #+ATTR_RST: :margin 4
   #+Begin_quote
   The subject, then, of Psychology is the uniformities of succession, the laws, whether ultimate or derivative, according to which one mental state succeeds another --- is caused by, or at least is caused to follow, another. -- [[https://books.google.ca/books?id=J0aijD0QQeoC&pg=PA39&lpg=PA39&dq=john+stuart+mill+elementary+laws+of+mind&source=bl&ots=cLXZn1c8AL&sig=ujStz3w3IcnsGzd9WtYDpjKggFQ&hl=en&sa=X&ved=0ahUKEwilyqGW34vMAhXBmIMKHXdIAfgQ6AEIHDAA#v=onepage&q&f=false][The Logic of the Moral Sciences]] (first published 1843). 
   #+End_quote

** Wilhelm Wundt

   #+ATTR_RST: :margin 4
   #+Begin_quote
   the investigation of conscious processes in the modes of connexion peculiar to them. -- Principles of Physiological Psychology ([[https://archive.org/stream/principlesphysi01wundgoog#page/n22/mode/2up][translation of the 5th edition]]) 1904
   #+End_quote

** Edward Bradford Titchener

   #+ATTR_RST: :margin 4
   #+Begin_quote
   the science of mental processes. --- [[https://archive.org/details/anoutlinepsycho01titcgoog][An Outline of Psychology]] 1902
   #+End_quote

** William James

   #+ATTR_RST: :margin 4
   #+Begin_quote
   Psychology is the Science of Mental Life, both of its phenomena and of their conditions. --- [[http://psychclassics.yorku.ca/James/Principles/prin1.htm][The Principles of Psychology]] 1890
   #+End_quote

** John Watson

   #+ATTR_RST: :margin 4
   #+Begin_quote
 Psychology as the behaviorist views it is a purely objective experimental branch of natural science. Its theoretical goal is the prediction and control of behavior. --- [[http://psychclassics.yorku.ca/Watson/views.htm][Psychology as the Behaviorist Views it]] 1913
   #+End_quote

** George Trumball Ladd and Robert Sessions Woodworth

   #+ATTR_RST: :margin 4
   #+Begin_quote
   We shall, therefore, consider psychology as that science which has for its primary subject of investigation all the phenomena of human consciousness, or of the sentient life of man. [[https://archive.org/stream/cu31924003161761#page/n7/mode/2up][Elements of Physiological Psychology]] 1911
   #+End_quote

** David G. Myers

   #+ATTR_RST: :margin 4
   #+Begin_quote
   the science of behavior and mental processes --- Psychology (10th Edition) 2013
   #+End_quote

* What’s in a name?
  “Psychology” comes from the Greek word “psyche” that means breath, life or soul and actually has an interesting myth tied to it. This myth depicts a great love story between Eros (Cupid in Latin), the son of Aphrodite and a mortal woman, named Psyche. In short, Psyche was considered to be the most beautiful mortal woman - even more beautiful than Aphrodite, the goddess of love and beauty. Out of jealousy, she sends her son to make Psyche fall in love with a terrible creature but accidentally scratches himself with his arrow with her in his sight. Eros falls in love with her, and after much trial and turbulence the two are wed and are no longer persecuted by Aphrodite. Psyche is made immortal and joins Eros in the sky.

* Some comments
   
As we shall see scientific psychology commences in the 1800s. Its origins are firmly established by those who want to connect physiological procedures and the physiologist's rigor with the psycho-physical principles of Fechner. Can we measure a thought they way we measure mass? Weight is how heavy things feel. Fechner claimed to have a procedure by which psychological intensity could be quantified, and related to physical intensity. If so, could we use this insight to develop a true science[fn:science] of inner experience? 

Many early scientific psychologists soon found this definition limiting, but more critically they found it a failure. Early controversies about whether or not thought required images, or how many elemental sensations there were left many psychologists despairing that a definition of psychology that focused on the mental could ever be the basis of progress. In a quest for objectivity in measurement the focus shifted to behavior, and this emphasis on behavior is still present in today's textbook definitions.

* A Few Final Questions

Does equating the science of psychology with the study of behavior make its practitioners more scientific? Does it do so at the expense of making them no longer psychologists? If psychology were to return to a pre-occupation with the mental (though we can try to avoid facing that by referring to it as  /cognitive/) does that mean its practitioners are no longer doing science?


[fn:science] And while thinking of definitions, ask yourself what makes something a science? Does psychology today meet that definition?
