#+Title: Women in Psychology's Early Years
#+Options: timestamp:nil

* Stub

** Ricord

** Calkins

** Washburn

** Ladd-Franklin

** Berliner
 Anna Berliner was born in 1888 and died in 1977. She was the first and only woman to receive a PhD under Wilhelm Wundt. Her main area of focus was in visual perception that extended into advertising and intelligence testing. Unfortunately, like most women she was overlooked in the history of psychology. 
Before her work in psychology, she studied medicine in Freiburg and Berlin. While in Berlin she fell in love with psychology after working at the Berlin Psychological Laboratory. In 1910 she married Sigfrid Berliner, a physicist who took a position at the University of Leipzig, where Anna pursued psychology. After working with a different supervisor, someone noted her interest in the field and that she should talk to Wundt. After going and talking to him and he accepted her, saying that he did not see any reason why she shouldn’t work for him. She did not study with him for long, but accumulated a lot of knowledge by working with Wundt in experimental psychology, the history of philosophy, and his Volkerpsychologie. In 1914 she completed her doctoral examination and received her PhD under Wundt. 
After leaving Leipzig, she and her husband moved to Japan and she worked as a consultant at an advertising firm. After World War I broke out, Anna was deported to the U.S., while her husband was believed to be an enemy alien. While in America, she studied at Berkeley and Columbia, publishing research on children’s judgments of beauty. 
By 1932, she and her husband were reunited, and by 1936 she was lecturing on visual psychology in Chicago, and became the chair and only member of the psychology department. Here, she taught on experimental psychology, statistics, perception, clinical psychology, personality, projective testing to name a few. She believed in the importance of the link between psychology and optometry, and applied the principles of visual psychology to various topics with her main focus being that “seeing is influenced by factors beyond the object of vision”.
In 1963 she was named a Lifetime Fellow of International Council of Psychologists, and received the Apollo Award (from the American Optometric Association) in 1971. 
In 1977 she was murdered in her home.
Her Legacy:
She was a teacher, a researchers and an applied psychologist
She helped women’s rights be becoming the first woman to ever work with Wundt
She was a professional, a critical thinker, a self-teacher, and always learning and applying her knowledge
Her famous words:
“An unused life is an earlier death” 
  ** source - http://www.apadivisions.org/division-35/about/heritage/anna-berliner-biography.aspx
